CREATE DATABASE goodfit;
USE goodfit;
CREATE TABLE cart_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_name VARCHAR(255),
  product_price INT,
  added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

